#!/bin/csh

cp ../DependTable_a ../DependTable << EOT
y
EOT
nimbus -b setup_tf01
nimbus -b setup_tf02
nimbus -b setup_tf03
#
nimbus -b setup_ff01a
nimbus -b setup_ff01b
nimbus -b setup_ff02
#
nimbus -b setup_rf01
nimbus -b setup_rf02
nimbus -b setup_rf03
nimbus -b setup_rf04
nimbus -b setup_rf05
nimbus -b setup_rf06
nimbus -b setup_rf07
nimbus -b setup_rf08
nimbus -b setup_rf09
nimbus -b setup_rf10
nimbus -b setup_rf11
nimbus -b setup_rf12
#nimbus -b setup_rf13
nimbus -b setup_rf13a
mv ${PROD_DIR}/305rf13.nc \
   ${PROD_DIR}/305rf13a.nc << EOT
y
EOT
cp ../DependTable_b ../DependTable << EOT
y
EOT
nimbus -b setup_rf13b
mv ${PROD_DIR}/305rf13.nc \
   ${PROD_DIR}/305rf13b.nc << EOT
y
EOT
nimbus -b setup_rf14
nimbus -b setup_rf15
nimbus -b setup_rf16
nimbus -b setup_rf17
nimbus -b setup_rf18
cp ../DependTable_a ../DependTable << EOT
y
EOT
nimbus -b setup_rf19
nimbus -b setup_rf20
nimbus -b setup_rf21
nimbus -b setup_rf22
nimbus -b setup_rf23
#
ncfixdate ${PROD_DIR}/305rf05.nc << EOT
08/28/2008
EOT

ncfixdate ${PROD_DIR}/305rf13b.nc << EOT
09/17/2008
EOT

ncfixdate ${PROD_DIR}/305rf15.nc << EOT
09/19/2008
EOT

ncfixdate ${PROD_DIR}/305rf18.nc << EOT
09/23/2008
EOT
