#!/bin/csh -f
#
#  "unrestrict" the DYCOMS-II data archived to the SCD Mass Store System
#   Written by Ron Ruth                                       8 Jan 2003
#
#echo "Began unrestricting MSS bitfiles on `date`"
#mspasswd -R -wpwd RAFDMG -rpwd DYCONLY -newr OFF /ATD/DATA/2001/DYCOMS-II/C130_N130AR
#mspasswd -R -wpwd RAFDMG -rpwd DYCONLY -newr OFF /RAF/2001/181
#echo "Finished unrestricting MSS bitfiles on `date`"
#
#  Done.
exit
#
# Began unrestricting MSS bitfiles on Fri Jan 10 11:54:54 MST 2003
# Finished unrestricting MSS bitfiles on Fri Jan 10 11:56:32 MST 2003
#
