#! /bin/csh -f
#
#   Rename raw ADS bitfiles for project 1999-803 MAP
#
#  Written by Ron Ruth using "102/Production/rename" as a template   2 Dec 1999
#
#   To find executable lines (from within `vi'), type:
#       /^[^#]
#
#  `vi' :map commands for annotating job completion:
#  :map g eea 
#  :map v AOK @ 
#
#  Get setup information for this project
set PRDIR = `pwd`
set PROJ = `echo $PRDIR | sed -e "s/[a-zA-Z\/]//g"`
set YEAR = `grep FY proj.info | sed -e "s/FY=//"`
#
#
#  Check login (only "dmg" login allowed to run this script)
set user = `whoami`
if ($user != "dmg") then
  echo ${0}:  Only the 'dmg' login is allowed to run this script.  Quitting.
  exit
endif
#
date
#
set OFILES = ( \
RF15 \
RF18 \
)
set NFILES = ( \
RF15A \
RF18A \
)
#
#  Get started:
set todo = $#OFILES
set num = 1
while ($num <= $todo)
  set OFILE = $OFILES[$num]
  set NFILE = $NFILES[$num]
  echo \
  nrnet msmv % r flnm=/RAF/$YEAR/$PROJ/$OFILE \
   newf=/RAF/$YEAR/$PROJ/$NFILE wpwd=RAFDMG
  @ num ++
end
#
# Done.
exit
#
# -----------------------------------------------------------------------------
#
#        Source directory:  /RAF/1999/803/
#   Destination directory:  /RAF/1999/803/
#
#  Job(s) submitted on Thu Dec  2 10:42:41 MST 1999
# Sequence number = LN0392 --  -- 
# Sequence number = LN0400 --  -- 
#

