#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Illegal number of parameters"
    echo "usage: update_ACE1_probe_metadata file_name.nc"
fi

ncatted -O -a DOI,global,c,c,'https://doi.org/10.5065/D6F18X1Z' --hdr_pad=8192 $1 tmp.nc
ncatted -O -a SizeDistributionLegacyZeroBin,global,c,c,'yes' tmp.nc
ncatted -O -a _FillValue,,c,f,-32767 tmp.nc

ncatted -O -a SerialNumber,A260X_IBR,c,c,'260X06' tmp.nc
ncatted -O -a units,A260X_IBR,o,c,'count' tmp.nc
ncatted -O -a Resolution,A260X_IBR,c,i,'10' tmp.nc
ncatted -O -a nDiodes,A260X_IBR,c,i,'64' tmp.nc
ncatted -O -a ResponseTime,A260X_IBR,c,f,'0.35' tmp.nc
ncatted -O -a ArmDistance,A260X_IBR,c,f,'61.0' tmp.nc
ncatted -O -a HistogramNote,A260X_IBR,c,c,'Zeroth data bin is an unused legacy placeholder.' tmp.nc

ncatted -O -a SerialNumber,C260X_IBR,c,c,'260X06' tmp.nc
ncatted -O -a FirstBin,C260X_IBR,c,i,'3' tmp.nc
ncatted -O -a LastBin,C260X_IBR,c,i,'62' tmp.nc
ncatted -O -a CellSizes,C260X_IBR,c,f,'15., 25., 35., 45., 55., 65., 75., 85., 95., 105., 115., 125., 135., 145., 155., 165., 175., 185., 195., 205., 215., 225., 235., 245., 255., 265., 275., 285., 295., 305., 315., 325., 335., 345., 355., 365., 375., 385., 395., 405., 415., 425., 435., 445., 455., 465., 475., 485., 495., 505., 515., 525., 535., 545., 555., 565., 575., 585., 595., 605., 615., 625., 635., 645' tmp.nc
ncatted -O -a CellSizeUnits,C260X_IBR,c,c,'micrometers' tmp.nc
ncatted -O -a CellSizeNote,C260X_IBR,c,c,'CellSizes are upper bin limits as diameter.' tmp.nc
ncatted -O -a HistogramNote,C260X_IBR,c,c,'Zeroth data bin is an unused legacy placeholder.' tmp.nc


ncatted -O -a SerialNumber,AFSSP_OBR,c,c,'FSSP122' tmp.nc
ncatted -O -a units,AFSSP_OBR,o,c,'count' tmp.nc
ncatted -O -a HistogramNote,AFSSP_OBR,c,c,'Zeroth data bin is an unused legacy placeholder.' tmp.nc

ncatted -O -a SerialNumber,CFSSP_OBR,c,c,'FSSP122' tmp.nc
ncatted -O -a FirstBin,CFSSP_OBR,c,i,'1' tmp.nc
ncatted -O -a LastBin,CFSSP_OBR,c,i,'15' tmp.nc
ncatted -O -a CellSizes,CFSSP_OBR,c,f,'2.0, 5.0, 8.0, 11.0, 14.0, 17.0, 20.0, 23.0, 26.0, 29.0, 32.0, 35.0, 38.0, 41.0, 44.0, 47.0' tmp.nc
ncatted -O -a CellSizeUnits,CFSSP_OBR,c,c,'micrometers' tmp.nc
ncatted -O -a CellSizeNote,CFSSP_OBR,c,c,'CellSizes are upper bin limits as diameter.' tmp.nc
ncatted -O -a HistogramNote,CFSSP_OBR,c,c,'Zeroth data bin is an unused legacy placeholder.' tmp.nc
ncatted -O -a DOF,CFSSP_OBR,c,f,'2.81' tmp.nc
ncatted -O -a BeamDiameter,CFSSP_OBR,c,f,'0.19' tmp.nc


ncatted -O -a SerialNumber,APCAS_RPI,c,c,'PCAS108' tmp.nc
ncatted -O -a units,APCAS_RPI,o,c,'count' tmp.nc
ncatted -O -a HistogramNote,APCAS_RPI,c,c,'Zeroth data bin is an unused legacy placeholder.' tmp.nc

ncatted -O -a SerialNumber,CPCAS_RPI,c,c,'PCAS108' tmp.nc
ncatted -O -a FirstBin,CPCAS_RPI,c,i,'1' tmp.nc
ncatted -O -a LastBin,CPCAS_RPI,c,i,'15' tmp.nc
ncatted -O -a CellSizes,CPCAS_RPI,c,f,'0.1, 0.12, 0.14, 0.17, 0.2, 0.25, 0.3, 0.4, 0.5, 0.7, 0.9, 1.2, 1.5, 2.0, 2.5, 3.0' tmp.nc
ncatted -O -a CellSizeUnits,CPCAS_RPI,c,c,'micrometers' tmp.nc
ncatted -O -a CellSizeNote,CPCAS_RPI,c,c,'CellSizes are upper bin limits as diameter.' tmp.nc
ncatted -O -a HistogramNote,CPCAS_RPI,c,c,'Zeroth data bin is an unused legacy placeholder.' tmp.nc


ncatted -O -a SerialNumber,AF300_RPO,c,c,'FSSP305' tmp.nc
ncatted -O -a units,AF300_RPO,o,c,'count' tmp.nc
ncatted -O -a HistogramNote,AF300_RPO,c,c,'Zeroth data bin is an unused legacy placeholder.' tmp.nc

ncatted -O -a SerialNumber,CF300_RPO,c,c,'FSSP305' tmp.nc
ncatted -O -a FirstBin,CF300_RPO,c,i,'1' tmp.nc
ncatted -O -a LastBin,CF300_RPO,c,i,'31' tmp.nc
ncatted -O -a CellSizes,CF300_RPO,c,f,'0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.8, 0.9, 1.0, 1.2, 1.4, 1.7, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 12.0, 14.0, 16.0, 18.0, 20.0' tmp.nc
ncatted -O -a CellSizeUnits,CF300_RPO,c,c,'micrometers' tmp.nc
ncatted -O -a CellSizeNote,CF300_RPO,c,c,'CellSizes are upper bin limits as diameter.' tmp.nc
ncatted -O -a HistogramNote,CF300_RPO,c,c,'Zeroth data bin is an unused legacy placeholder.' tmp.nc
