#! /bin/csh -f
ncmerge -v DPLA,DPLA1,RHLA,RHLA1 131rf01.cdf 131rf01LA.cdf
ncmerge -v DPLA,DPLA1,RHLA,RHLA1 131rf02.cdf 131rf02LA.cdf
ncmerge -v DPLA,DPLA1,RHLA,RHLA1 131rf03.cdf 131rf03LA.cdf
ncmerge -v DPLA,DPLA1,RHLA,RHLA1 131rf04.cdf 131rf04LA.cdf
ncmerge -v DPLA,DPLA1,RHLA,RHLA1 131rf05.cdf 131rf05LA.cdf
ncmerge -v DPLA,DPLA1,RHLA,RHLA1 131rf06.cdf 131rf06LA.cdf
ncmerge -v DPLA,DPLA1,RHLA,RHLA1 131rf07.cdf 131rf07LA.cdf
ncmerge -v DPLA,DPLA1,RHLA,RHLA1 131rf08.cdf 131rf08LA.cdf
ncmerge -v DPLA,DPLA1,RHLA,RHLA1 131rf09.cdf 131rf09LA.cdf
ncmerge -v DPLA,DPLA1,RHLA,RHLA1 131rf10.cdf 131rf10LA.cdf
ncmerge -v DPLA,DPLA1,RHLA,RHLA1 131rf11.cdf 131rf11LA.cdf
ncmerge -v DPLA,DPLA1,RHLA,RHLA1 131rf12.cdf 131rf12LA.cdf
ncmerge -v DPLA,DPLA1,RHLA,RHLA1 131rf13.cdf 131rf13LA.cdf
ncmerge -v DPLA,DPLA1,RHLA,RHLA1 131rf14.cdf 131rf14LA.cdf
ncmerge -v DPLA,DPLA1,RHLA,RHLA1 131rf15.cdf 131rf15LA.cdf
ncmerge -v DPLA,DPLA1,RHLA,RHLA1 131rf16.cdf 131rf16LA.cdf
ncmerge -v DPLA,DPLA1,RHLA,RHLA1 131rf17.cdf 131rf17LA.cdf
ncmerge -v DPLA,DPLA1,RHLA,RHLA1 131rf18.cdf 131rf18LA.cdf
ncmerge -v DPLA,DPLA1,RHLA,RHLA1 131rf19.cdf 131rf19LA.cdf
exit
