C** RHUMLA - RELATIVE HUMIDITY CALCULATION (PERCENT)
        IF ((LDLA.AND.IPRHUMLA.GT.0) .OR. (LDLA1.AND.IPRHUML1.GT.0))
         CALL SEWIC (DPLA,PSXC,EDPC)
         CALL SEWIC (ATX,PSXC,EATX)
         IF (EATX.EQ.0.0) EATX = 0.0001
         RHUM = 100.*EDPC/EATX
        ENDIF
